# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript
trigger:
- master
pool:
  vmImage: ubuntu-latest

jobs:
- job: Build
steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'
- script: |
    npm install
    npm run build
  displayName: 'npm install and build'
  
- job: Lint
  displayName: 'Run ESLint'
  steps:
  - script: npm install
    displayName: 'Install Dependencies'
  - script: npx eslint .
    displayName: 'Run ESLint'